# Generated by Django 5.1.4 on 2024-12-13 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Image',
        ),
    ]
